# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workbench', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodrecordworkbench',
            options={'verbose_name': 'Food Record', 'verbose_name_plural': 'Food Records'},
        ),
    ]
