# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workbench', '0002_auto_20161024_1442'),
        ('Bibliography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref',
            name='wb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Workbench.Workbench'),
        ),
    ]
