# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliography', '0002_ref_wb'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_name_ascii',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name_ascii',
            field=models.CharField(max_length=255),
        ),
    ]
