# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('col_taxon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('col_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(db_index=True, max_length=255)),
                ('taxon_rank', models.CharField(max_length=255, blank=True, null=True)),
                ('taxon_status', models.CharField(db_index=True, max_length=255, blank=True, null=True)),
                ('accepted_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taxon_acceptednameset', to='Taxonomy.Taxon')),
                ('parent_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taxon_parentnameset', to='Taxonomy.Taxon')),
                ('author', models.CharField(max_length=255, blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'taxa',
                'db_table': 'sb_taxon',
            },
        ),
        migrations.CreateModel(
            name='TaxonAmphibian',
            fields=[
                ('col_taxon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('col_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(max_length=255)),
                ('taxon_rank', models.CharField(max_length=255)),
                ('taxon_status', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255, blank=True, null=True)),
            ],
            options={
                'managed': False,
                'abstract': False,
                'db_table': 'sb_taxon_amphibian',
            },
        ),
        migrations.CreateModel(
            name='TaxonAnimal',
            fields=[
                ('col_taxon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('col_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(max_length=255)),
                ('taxon_rank', models.CharField(max_length=255)),
                ('taxon_status', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255, blank=True, null=True)),
            ],
            options={
                'managed': False,
                'abstract': False,
                'db_table': 'sb_taxon_animal',
            },
        ),
        migrations.CreateModel(
            name='TaxonAnnelid',
            fields=[
                ('col_taxon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('col_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(max_length=255)),
                ('taxon_rank', models.CharField(max_length=255)),
                ('taxon_status', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255, blank=True, null=True)),
            ],
            options={
                'managed': False,
                'abstract': False,
                'db_table': 'sb_taxon_annelid',
            },
        ),
        migrations.CreateModel(
            name='TaxonArthropod',
            fields=[
                ('col_taxon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('col_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(max_length=255)),
                ('taxon_rank', models.CharField(max_length=255)),
                ('taxon_status', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255, blank=True, null=True)),
            ],
            options={
                'managed': False,
                'abstract': False,
                'db_table': 'sb_taxon_arthropod',
            },
        ),
        migrations.CreateModel(
            name='TaxonBird',
            fields=[
                ('col_taxon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('col_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(max_length=255)),
                ('taxon_rank', models.CharField(max_length=255)),
                ('taxon_status', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255, blank=True, null=True)),
            ],
            options={
                'managed': False,
                'abstract': False,
                'db_table': 'sb_taxon_bird',
            },
        ),
        migrations.CreateModel(
            name='TaxonFish',
            fields=[
                ('col_taxon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('col_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(max_length=255)),
                ('taxon_rank', models.CharField(max_length=255)),
                ('taxon_status', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255, blank=True, null=True)),
            ],
            options={
                'managed': False,
                'abstract': False,
                'db_table': 'sb_taxon_fish',
            },
        ),
        migrations.CreateModel(
            name='TaxonFungus',
            fields=[
                ('col_taxon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('col_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(max_length=255)),
                ('taxon_rank', models.CharField(max_length=255)),
                ('taxon_status', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255, blank=True, null=True)),
            ],
            options={
                'managed': False,
                'abstract': False,
                'db_table': 'sb_taxon_fungus',
            },
        ),
        migrations.CreateModel(
            name='TaxonMammal',
            fields=[
                ('col_taxon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('col_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(max_length=255)),
                ('taxon_rank', models.CharField(max_length=255)),
                ('taxon_status', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255, blank=True, null=True)),
            ],
            options={
                'managed': False,
                'abstract': False,
                'db_table': 'sb_taxon_mammal',
            },
        ),
        migrations.CreateModel(
            name='TaxonMollusk',
            fields=[
                ('col_taxon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('col_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(max_length=255)),
                ('taxon_rank', models.CharField(max_length=255)),
                ('taxon_status', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255, blank=True, null=True)),
            ],
            options={
                'managed': False,
                'abstract': False,
                'db_table': 'sb_taxon_mollusk',
            },
        ),
        migrations.CreateModel(
            name='TaxonOnychophoran',
            fields=[
                ('col_taxon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('col_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(max_length=255)),
                ('taxon_rank', models.CharField(max_length=255)),
                ('taxon_status', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255, blank=True, null=True)),
            ],
            options={
                'managed': False,
                'abstract': False,
                'db_table': 'sb_taxon_onychophoran',
            },
        ),
        migrations.CreateModel(
            name='TaxonPlant',
            fields=[
                ('col_taxon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('col_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(max_length=255)),
                ('taxon_rank', models.CharField(max_length=255)),
                ('taxon_status', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255, blank=True, null=True)),
            ],
            options={
                'managed': False,
                'abstract': False,
                'db_table': 'sb_taxon_plant',
            },
        ),
        migrations.CreateModel(
            name='TaxonReptile',
            fields=[
                ('col_taxon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('col_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(max_length=255)),
                ('taxon_rank', models.CharField(max_length=255)),
                ('taxon_status', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255, blank=True, null=True)),
            ],
            options={
                'managed': False,
                'abstract': False,
                'db_table': 'sb_taxon_reptile',
            },
        ),
    ]
