# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OntologyCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sb_ontology_collection',
            },
        ),
        migrations.CreateModel(
            name='OntologyRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
            ],
            options={
                'db_table': 'sb_ontology_relationship',
            },
        ),
        migrations.CreateModel(
            name='OntologyTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('definition', models.TextField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Glossary.OntologyCollection')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Glossary.OntologyTerm')),
            ],
            options={
                'db_table': 'sb_ontology_term',
            },
        ),
        migrations.CreateModel(
            name='OntologyHasRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontology_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ontology_fromset', to='Glossary.OntologyTerm')),
                ('ontology_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ontology_toset', to='Glossary.OntologyTerm')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Glossary.OntologyRelationship')),
            ],
            options={
                'db_table': 'sb_ontology_has_relationship',
                'verbose_name': 'relationship',
            },
        ),
    ]
