# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodRecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecord',
            name='alimentary_pos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodrecord',
            name='ingestion_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foodrecord_ingestedset', to='Glossary.OntologyTerm'),
        ),
    ]
