# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workbench', '0001_initial'),
        ('FoodRecord', '0002_auto_20160919_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecord',
            name='wb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Workbench.Workbench'),
        ),
    ]
