# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodRecord', '0003_auto_20161023_1315'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dataset',
            table='sb_frdataset',
        ),
        migrations.AlterModelTable(
            name='datasetfoodrecord',
            table='sb_frdataset_foodrecord',
        ),
        migrations.AlterModelTable(
            name='datasetlocality',
            table='sb_frdataset_locality',
        ),
        migrations.AlterModelTable(
            name='datasetmethod',
            table='sb_frdataset_method',
        ),
    ]
