# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 15:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Glossary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdmUnit',
            fields=[
                ('geoname_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_level', models.IntegerField()),
                ('unit_name_ascii', models.CharField(max_length=255)),
                ('unit_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Administrative unit',
                'verbose_name_plural': 'Administrative units',
                'db_table': 'sb_adm',
            },
        ),
        migrations.CreateModel(
            name='AdmUnitBoundary',
            fields=[
                ('geoname_id', models.OneToOneField(db_column='geoname_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Geography.AdmUnit')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Administrative unit shapefile',
                'verbose_name_plural': 'Administrative unit shapefiles',
                'db_table': 'sb_adm_boundary',
            },
        ),
        migrations.CreateModel(
            name='NamedPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm0', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='namedplace_countryset', to='Geography.AdmUnit')),
                ('adm1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='namedplace_stateset', to='Geography.AdmUnit')),
                ('adm2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='namedplace_countyset', to='Geography.AdmUnit')),
                ('place_name', models.CharField(max_length=255)),
                ('verbatim_coordinates', models.CharField(blank=True, null=True, max_length=255)),
                ('verbatim_srid', models.ForeignKey(blank=True, db_column='srid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Geography.SpatialRefSys')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('elevation_start', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('elevation_end', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('elevation_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Glossary.OntologyTerm')),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Place name',
                'verbose_name_plural': 'Place names',
                'db_table': 'sb_namedplace',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm0', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locality_countryset', to='Geography.AdmUnit')),
                ('adm1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locality_stateset', to='Geography.AdmUnit')),
                ('adm2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locality_countyset', to='Geography.AdmUnit')),
                ('named_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Geography.NamedPlace')),
                ('dirtmap', models.CharField(blank=True, max_length=255, null=True)),
                ('verbatim_coordinates', models.CharField(blank=True, null=True, max_length=255)),
                ('verbatim_srid', models.ForeignKey(blank=True, db_column='srid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Geography.SpatialRefSys')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('coordinate_uncertainty', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('uncertainty_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locality_uncertaintyunitset', to='Glossary.OntologyTerm')),
                ('georeferenced_from', models.CharField(blank=True, max_length=255, null=True)),
                ('elevation_start', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('elevation_end', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('elevation_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locality_elevationunitset', to='Glossary.OntologyTerm')),
                ('verbatim_elevation', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Locality',
                'verbose_name_plural': 'Localities',
                'db_table': 'sb_locality',
            },
        ),
        migrations.AddField(
            model_name='admunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Geography.AdmUnit'),
        ),
    ]
