# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('museum_name', models.CharField(max_length=255)),
                ('museum_abbr', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sb_museum',
            },
        ),
        migrations.CreateModel(
            name='MuseumCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MuseumCatalog.Museum')),
                ('collection_name', models.CharField(max_length=255)),
                ('collection_code', models.CharField(max_length=255, blank=True, null=True)),
            ],
            options={
                'db_table': 'sb_museum_collection',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MuseumCatalog.Museum')),
                ('museum_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MuseumCatalog.MuseumCollection')),
                ('catalog_number', models.CharField(blank=True, max_length=255, null=True)),
                ('field_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sb_voucher',
            },
        ),
    ]
